import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useRouter } from 'next/router'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {  
  const router = useRouter();

  const handleClick = () => {
    console.log("you clicked the button");
    router.push('/home')
    
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h2>Basic Routing Task</h2>
        <Link href={'/home'}>
          Home
        </Link>
        <br />
        <Link href={'./multipleNestedRouting'}>
          Multiple Nested Routing
        </Link>
        <br />
        <Link href={'./dynamicRouting/23'}>
          Dynamic Routing
        </Link>
        <br />
        <Link href={'./docs'}>
          Docs</Link>
          <button onClick={handleClick}>Click Me</button>
      </div>

    </div>
  )
}

export default Home
